clear-button
tylergraf/chits pull request #5
Opened 2018-08-11 18:36 UTC by zeroadh

clear button and _clearChit method on hole-page.js

2018-08-11 18:53 UTC, tylergraf requested changes

2018-08-11 18:53 UTC, tylergraf commented on src/components/hole-page.js
> +    hole.chits = hole.chits.filter(chit=>chit._id !=== chitID);
Should be `chitId` here. (lowercase d)

2018-08-11 18:53 UTC, tylergraf commented on src/components/hole-page.js
> +    hole.chits = hole.chits.filter(chit=>chit._id !=== chitID);
Also, should be `!==`.

2018-08-11 19:03 UTC, tylergraf requested changes

2018-08-11 19:03 UTC, tylergraf commented on src/components/hole-page.js
> +        <button on-click="${e=>this._clearChit(e, hole, chitId)}">Clear</button>
Sorry, should be `_hole` and `chit._id` here.

2018-08-11 20:29 UTC, zeroadh commented on src/components/hole-page.js
> +        <button on-click="${e=>this._clearChit(e, hole, chitId)}">Clear</button>
Right...those should've been the actual variables passed as parameters in that method.  Sorry.  Fixed it.

2018-08-12 00:23 UTC, tylergraf commented
Looks great!

2018-08-12 00:23 UTC, merged